name: Build

on:
  push:
    tags:
      - "*.*"

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main
      - name: ADB
        run: |
          $Parameters = @{
             Path             = "src"
             DestinationPath  = "ADB.zip"
             CompressionLevel = "Fastest"
             Force            = $true
          }
          Compress-Archive @Parameters

      - name: Uploading
        # https://github.com/softprops/action-gh-release/issues/556
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974
        with:
          name: ${{ env.RELEASE_NAME }}
          token: ${{ github.token }}
          files: ADB.zip
